### ISSUE TITLE
Change History Panel Commit Message Error

### ISSUE THREAD

**Issue by compleatguru** [archi-contribs/archi-modelrepository-plugin#38] opened 2017-06-27 16:47 UTC
When I had made 1 local commit and then pushed successfully to the remote repo, the commit message is still showing [local] instead of [remote] prefix.

**Comment by Phillipus** [comment] 2017-06-27 16:55
Does it show [local/remote] if you deselect and reselect the model?

**Comment by jbsarrodie** [comment] 2017-06-27 17:56
@Phillipus this seems very similar to an issue I faced some time ago. That's what I had in mind when creating #26 whithout being able to remember exactly what. Now we know

**Comment by Phillipus** [comment] 2017-06-27 18:21
I can't reproduce it.

**Comment by jbsarrodie** [comment] 2017-06-27 18:23
>I can't reproduce it.

The question is: which version does @compleatguru use? Is it the 0.2.1 (which I think does not include your latest fixes) or current master

**Comment by Phillipus** [comment] 2017-06-27 18:25
I'll make another build. @compleatguru can try that.

**Comment by Phillipus** [comment] 2017-07-03 09:56
It seems likely that a push action is not happening, and it is failing quietly. I've just released version 0.2.2 of the plugin. Could you try that and see if it helps?

**Comment by Phillipus** [comment] 2017-07-17 16:41
Closing.

**Closed by Phillipus** 2017-07-17 16:41 UTC
